# for further structuring check https://docs.gitlab.com/ee/ci/yaml/
enerx:
  image: everken/enerx:python3.7-cbc2.9
  script:
    - export SOLVER="cbc"
    - pip install -e .
    - pytest --cov=tsib --cov-report tsib