pytest:
  stage: test
  image: python:slim-buster
  script:
    - pip install --no-cache-dir -e .
    - export SOLVER="highs"
    - pip install codecov
    - pip install pytest
    - pip install pytest-cov
    - pytest --cov=tsib/ test/
