language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - export SOLVER="highs"
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install --no-cache-dir -e .
script:
  - pytest --cov=./tsib

after_success:
  - codecov